apiVersion: v1
kind: Secret
metadata:
  name: django-secret
  namespace: argocd-new
  labels:
    app: django-app
type: Opaque
data:
  SECRET_KEY: ZGphbmdvLWluc2VjdXJlLXlvdXItc2VjcmV0LWtleS1oZXJl # base64 encoded
  POSTGRES_PASSWORD: cG9zdGdyZXM= # base64 encoded "postgres"
